### ISSUE TITLE
Awaiting confirmation from Bambora

### ISSUE THREAD

**Issue by Freakshows** [bambora/checkout-opencart#13]
All day i have had transaction with this message:
_Awaiting confirmation from Bambora_
And not the usual details, did something changed? see attachments
Transactions shows ok in bambora merchant dashboard
![bambora1](https://user-images.githubusercontent.com/13005141/43285546-8d11a1de-911f-11e8-9a5a-76f96ec0f2d7.PNG)
![bambora2](https://user-images.githubusercontent.com/13005141/43285553-94bb6596-911f-11e8-9a34-4335318fe2c9.PNG)

**Comment by AllanWLie** [comment]
Hi @Freakshows 

Seems like you did not receive the callback. I order for us to investigate your issue we need your merchant and transaction infomations. So please write a support ticket to support@bambora.com with the infomation.

(We are currently under staffed because of vacations, so please be patient)

Best regards
Allan - Bambora

**Comment by syntaxerror** [comment]
I just want to add to it ...

I also recommend checking with the host, if they did change anything on the server, that might block calls from Bambora. I've sometimes found they have updated suhosin/modescurity etc., adding new rules blocking external payment responses.

But, sometimes it just takes extra time too, if the server was down/having high load on first callback attempt ...
