### ISSUE TITLE
Internet Explorer?

### ISSUE THREAD

**Issue by Freakshows** [bambora/checkout-opencart#15]
Now and then i get feedback from customers that when they clicking the pay now button, nothing happens. When i am able to ask the customer what browser he/she is using the answer is often IE. Personaly i dont like IE, but even so, i have two payment methods in my store, bambora and the native PP Express, PP Express seems to be of help if customer dont get a response from bambora pay now button.

Thoughts?

**Comment by syntaxerror** [comment]
When it comes to IE, the version of it is important to know.
Maybe a javascript issue ...?

Btw! Which version of the module do you have in use? Newer than 1.2.0?
I'm asking because there was this change in 1.2.1: https://github.com/bambora/checkout-opencart/commit/824cd85ba99247da0980c0bafbd1b7f953d49a27
And again in 1.2.3: https://github.com/bambora/checkout-opencart/commit/d5435e885bdaa92b9c005c5b01e84097472dbbdb
