### ISSUE TITLE
Wrong payment authorize from card

### ISSUE THREAD

**Issue by tlombert** [bambora/checkout-opencart#26]
Hi

We have got several wrong card authorization under a couple of weeks. It looks like there are EUR payment with card. I attach two orders there one is lower than the OC order and one is higher the OC order. One of this is with the last version and one is with the last version.
We have OC 3.0.3.2.

**Comment by sessan** [comment]
Hi! Could you contact support@bambora.com with the further details on the orders and the transactions that are having these issues? What extra modules you are using etc. I will remove the images with the transaction details here since GitHub here is open to the public. Please also add the details about exactly what version of our plugin you used and of OC. 
Best Regards
Jessica Björkäng - Bambora Online

**Comment by sessan** [comment]
Have not heard more regarding this so closing.
